name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install openssh-client

    - name: Deploy via SSH
      run: echo "Deploying to server"

    - name: Deploy via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: echo "$SSH_PRIVATE_KEY"

    - name: Run Command via SSH
      uses: appleboy/ssh-action@master
      with:
        host: carpass.fi
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          ls -l